# Generated by Django 4.0.4 on 2022-06-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_venue_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='slug',
        ),
    ]
